/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TerrainEditor.GUILAYOUTS;

/**
 *
 * @author K
 */
public class NewJFrame extends javax.swing.JFrame
{

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jButton135 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton137 = new javax.swing.JButton();
        jButton138 = new javax.swing.JButton();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton141 = new javax.swing.JButton();
        jButton142 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jButton144 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(768, 768));
        jPanel2.setLayout(new java.awt.GridLayout());

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setFocusTraversalPolicyProvider(true);
        jPanel3.setLayout(new java.awt.GridLayout(12, 12));

        jButton1.setText("(11,11)");
        jPanel3.add(jButton1);

        jButton13.setText("jButton13");
        jPanel3.add(jButton13);

        jButton16.setText("jButton16");
        jPanel3.add(jButton16);

        jButton20.setText("jButton20");
        jPanel3.add(jButton20);

        jButton19.setText("jButton19");
        jPanel3.add(jButton19);

        jButton24.setText("jButton24");
        jButton24.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton24);

        jButton27.setText("jButton27");
        jPanel3.add(jButton27);

        jButton26.setText("jButton26");
        jPanel3.add(jButton26);

        jButton32.setText("jButton32");
        jPanel3.add(jButton32);

        jButton35.setText("jButton35");
        jPanel3.add(jButton35);

        jButton34.setText("jButton34");
        jPanel3.add(jButton34);

        jButton31.setText("jButton31");
        jPanel3.add(jButton31);

        jButton30.setText("jButton30");
        jPanel3.add(jButton30);

        jButton23.setText("jButton23");
        jPanel3.add(jButton23);

        jButton25.setText("jButton25");
        jPanel3.add(jButton25);

        jButton28.setText("jButton28");
        jPanel3.add(jButton28);

        jButton22.setText("jButton22");
        jPanel3.add(jButton22);

        jButton21.setText("jButton21");
        jPanel3.add(jButton21);

        jButton33.setText("jButton33");
        jPanel3.add(jButton33);

        jButton29.setText("jButton29");
        jPanel3.add(jButton29);

        jButton18.setText("jButton18");
        jPanel3.add(jButton18);

        jButton17.setText("jButton17");
        jPanel3.add(jButton17);

        jButton14.setText("jButton14");
        jPanel3.add(jButton14);

        jButton15.setText("jButton15");
        jPanel3.add(jButton15);

        jButton2.setText("(11,9)");
        jPanel3.add(jButton2);

        jButton36.setText("jButton13");
        jPanel3.add(jButton36);

        jButton37.setText("jButton16");
        jPanel3.add(jButton37);

        jButton38.setText("jButton20");
        jPanel3.add(jButton38);

        jButton39.setText("jButton19");
        jPanel3.add(jButton39);

        jButton40.setText("jButton24");
        jButton40.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton40);

        jButton3.setText("jButton1");
        jPanel3.add(jButton3);

        jButton41.setText("jButton13");
        jPanel3.add(jButton41);

        jButton42.setText("jButton16");
        jPanel3.add(jButton42);

        jButton43.setText("jButton20");
        jPanel3.add(jButton43);

        jButton44.setText("jButton19");
        jPanel3.add(jButton44);

        jButton45.setText("jButton24");
        jButton45.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton45);

        jButton4.setText("jButton1");
        jPanel3.add(jButton4);

        jButton46.setText("jButton13");
        jPanel3.add(jButton46);

        jButton47.setText("jButton16");
        jPanel3.add(jButton47);

        jButton48.setText("jButton20");
        jPanel3.add(jButton48);

        jButton49.setText("jButton19");
        jPanel3.add(jButton49);

        jButton50.setText("jButton24");
        jButton50.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton50);

        jButton5.setText("jButton1");
        jPanel3.add(jButton5);

        jButton51.setText("jButton13");
        jPanel3.add(jButton51);

        jButton52.setText("jButton16");
        jPanel3.add(jButton52);

        jButton53.setText("jButton20");
        jPanel3.add(jButton53);

        jButton54.setText("jButton19");
        jPanel3.add(jButton54);

        jButton55.setText("jButton24");
        jButton55.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton55);

        jButton6.setText("(11,7)");
        jPanel3.add(jButton6);

        jButton56.setText("jButton13");
        jPanel3.add(jButton56);

        jButton57.setText("jButton16");
        jPanel3.add(jButton57);

        jButton58.setText("jButton20");
        jPanel3.add(jButton58);

        jButton59.setText("jButton19");
        jPanel3.add(jButton59);

        jButton60.setText("jButton24");
        jButton60.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton60);

        jButton7.setText("jButton1");
        jPanel3.add(jButton7);

        jButton61.setText("jButton13");
        jPanel3.add(jButton61);

        jButton62.setText("jButton16");
        jPanel3.add(jButton62);

        jButton63.setText("jButton20");
        jPanel3.add(jButton63);

        jButton64.setText("jButton19");
        jPanel3.add(jButton64);

        jButton65.setText("jButton24");
        jButton65.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton65);

        jButton8.setText("jButton1");
        jPanel3.add(jButton8);

        jButton66.setText("jButton24");
        jButton66.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton66);

        jButton67.setText("jButton34");
        jPanel3.add(jButton67);

        jButton68.setText("jButton28");
        jPanel3.add(jButton68);

        jButton69.setText("jButton18");
        jPanel3.add(jButton69);

        jButton70.setText("jButton13");
        jPanel3.add(jButton70);

        jButton9.setText("jButton1");
        jPanel3.add(jButton9);

        jButton71.setText("jButton24");
        jButton71.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton71);

        jButton72.setText("jButton19");
        jPanel3.add(jButton72);

        jButton73.setText("jButton20");
        jPanel3.add(jButton73);

        jButton74.setText("jButton16");
        jPanel3.add(jButton74);

        jButton75.setText("jButton13");
        jPanel3.add(jButton75);

        jButton10.setText("(11,5)");
        jPanel3.add(jButton10);

        jButton76.setText("jButton24");
        jButton76.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton76);

        jButton77.setText("jButton34");
        jPanel3.add(jButton77);

        jButton78.setText("jButton28");
        jPanel3.add(jButton78);

        jButton79.setText("jButton18");
        jPanel3.add(jButton79);

        jButton80.setText("jButton13");
        jPanel3.add(jButton80);

        jButton11.setText("jButton1");
        jPanel3.add(jButton11);

        jButton81.setText("jButton24");
        jButton81.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton81);

        jButton82.setText("jButton19");
        jPanel3.add(jButton82);

        jButton83.setText("jButton20");
        jPanel3.add(jButton83);

        jButton84.setText("jButton16");
        jPanel3.add(jButton84);

        jButton85.setText("jButton13");
        jPanel3.add(jButton85);

        jButton12.setText("jButton1");
        jPanel3.add(jButton12);

        jButton86.setText("jButton24");
        jButton86.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton86);

        jButton87.setText("jButton34");
        jPanel3.add(jButton87);

        jButton88.setText("jButton28");
        jPanel3.add(jButton88);

        jButton89.setText("jButton18");
        jPanel3.add(jButton89);

        jButton90.setText("jButton13");
        jPanel3.add(jButton90);

        jButton91.setText("jButton1");
        jPanel3.add(jButton91);

        jButton92.setText("jButton24");
        jButton92.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton92);

        jButton93.setText("jButton19");
        jPanel3.add(jButton93);

        jButton94.setText("jButton20");
        jPanel3.add(jButton94);

        jButton95.setText("jButton16");
        jPanel3.add(jButton95);

        jButton96.setText("jButton13");
        jPanel3.add(jButton96);

        jButton97.setText("(11,3)");
        jPanel3.add(jButton97);

        jButton98.setText("jButton24");
        jButton98.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton98);

        jButton99.setText("jButton34");
        jPanel3.add(jButton99);

        jButton100.setText("jButton28");
        jPanel3.add(jButton100);

        jButton101.setText("jButton18");
        jPanel3.add(jButton101);

        jButton102.setText("jButton13");
        jPanel3.add(jButton102);

        jButton103.setText("jButton1");
        jPanel3.add(jButton103);

        jButton104.setText("jButton24");
        jButton104.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton104);

        jButton105.setText("jButton19");
        jPanel3.add(jButton105);

        jButton106.setText("jButton20");
        jPanel3.add(jButton106);

        jButton107.setText("jButton16");
        jPanel3.add(jButton107);

        jButton108.setText("jButton13");
        jPanel3.add(jButton108);

        jButton109.setText("jButton1");
        jPanel3.add(jButton109);

        jButton110.setText("jButton24");
        jButton110.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton110);

        jButton111.setText("jButton34");
        jPanel3.add(jButton111);

        jButton112.setText("jButton28");
        jPanel3.add(jButton112);

        jButton113.setText("jButton18");
        jPanel3.add(jButton113);

        jButton114.setText("jButton13");
        jPanel3.add(jButton114);

        jButton115.setText("jButton1");
        jPanel3.add(jButton115);

        jButton116.setText("jButton24");
        jButton116.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton116);

        jButton117.setText("jButton19");
        jPanel3.add(jButton117);

        jButton118.setText("jButton20");
        jPanel3.add(jButton118);

        jButton119.setText("jButton16");
        jPanel3.add(jButton119);

        jButton120.setText("jButton13");
        jPanel3.add(jButton120);

        jButton121.setText("(11,1)");
        jPanel3.add(jButton121);

        jButton122.setText("jButton24");
        jButton122.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton122);

        jButton123.setText("jButton34");
        jPanel3.add(jButton123);

        jButton124.setText("jButton28");
        jPanel3.add(jButton124);

        jButton125.setText("jButton18");
        jPanel3.add(jButton125);

        jButton126.setText("jButton13");
        jPanel3.add(jButton126);

        jButton127.setText("jButton1");
        jPanel3.add(jButton127);

        jButton128.setText("jButton24");
        jButton128.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton128);

        jButton129.setText("jButton19");
        jPanel3.add(jButton129);

        jButton130.setText("jButton20");
        jPanel3.add(jButton130);

        jButton131.setText("jButton16");
        jPanel3.add(jButton131);

        jButton132.setText("jButton13");
        jPanel3.add(jButton132);

        jButton133.setText("(11,0)");
        jPanel3.add(jButton133);

        jButton134.setText("(10,0)");
        jButton134.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton134);

        jButton135.setText("jButton34");
        jPanel3.add(jButton135);

        jButton136.setText("(8,0)");
        jPanel3.add(jButton136);

        jButton137.setText("jButton18");
        jPanel3.add(jButton137);

        jButton138.setText("(6,0)");
        jPanel3.add(jButton138);

        jButton139.setText("jButton1");
        jPanel3.add(jButton139);

        jButton140.setText("(4,0)");
        jButton140.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jButton140);

        jButton141.setText("jButton19");
        jPanel3.add(jButton141);

        jButton142.setText("(2,0)");
        jPanel3.add(jButton142);

        jButton143.setText("(1,0)");
        jPanel3.add(jButton143);

        jButton144.setText("(0,0)");
        jPanel3.add(jButton144);

        jPanel2.add(jPanel3);

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton142;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
